# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('liked_count', models.PositiveIntegerField(default=0)),
                ('collection_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.User')),
                ('collection', models.ManyToManyField(related_name='collection', to='user.User')),
            ],
            options={
                'db_table': 'article_data',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'comment_data',
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='article.Article')),
            ],
            options={
                'db_table': 'moment_data',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(to='article.Comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='user.User'),
        ),
        migrations.AlterUniqueTogether(
            name='moment',
            unique_together=set([('author', 'time')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('author', 'time')]),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('title', 'author')]),
        ),
    ]
