# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171011_2023'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('title', 'author')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('author', 'time')]),
        ),
    ]
