# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171011_2023'),
        ('article', '0002_auto_20171216_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='user.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='user.User'),
        ),
    ]
