# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171011_2023'),
        ('article', '0003_auto_20171216_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collection',
            field=models.ManyToManyField(related_name='collection', to='user.User'),
        ),
    ]
