# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collection_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
