# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='liked',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
